publish_to: none
name: mega_delivery
description: 'App móvil de pedidos on line de Megacenter con la que llegamos a tu casa'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.1+20

environment:
   sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons
  google_map_location_picker:
    git:
      url: https://github.com/lyokone/google_map_location_picker.git
  get_version:
    git:
      url: https://github.com/Creky/get_version.git
  # place_picker:
  #   git:
  #     url: https://github.com/mo-ah-dawood/locationpicker.git
  #     ref: nullsafety
  
  cupertino_icons: ^1.0.4
  google_maps_flutter: ^2.2.0
  mvc_pattern: 6.3.0
  global_configuration: ^2.0.0-nullsafety.1
  http: ^0.13.4
  html: ^0.15.0
  shared_preferences: ^2.0.13
  flutter_html: ^2.1.5
  flutter_svg: 0.22.0
  location: ^4.3.0
  flutter_inappwebview: ^5.4.1+1
  url_launcher: ^6.1.0
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: 0.3.2
  intl_utils: ^2.6.1
  carousel_slider: ^4.1.1
  firebase_messaging: ^11.2.14
  firebase_core: ^1.15.0
  flutter_credit_card: ^3.0.1
  flutter_secure_storage: ^5.0.2
  # place_picker: 
  #   git:
  #     url: https://github.com/blackmann/locationpicker

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/cfg/
    - assets/img/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: ProductSans
    fonts:
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/ProductSans-Thin.ttf
        weight: 200
      - asset: assets/fonts/ProductSans-Light.ttf
        weight: 300
      - asset: assets/fonts/ProductSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/ProductSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/ProductSans-Bold.ttf
        weight: 600
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 700
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 800
      - asset: assets/fonts/ProductSans-Black.ttf
        weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-assets/fonts/#from-packages
flutter_intl:
  enabled: true



#just for the testing